# Sesión 2 Introducción a Numpy y fors
En esta sesión trabajaremos los conceptos básicos de la libreria numpy y introduciremos los buvles fors


### Instrucciones Jupyter notebook
* ctrl + enter = ejecutar celda
* shift + enter = ejecutar celda y pasar a la siguiente
* Esc + M = transformar celda en texto markdown
* Esc + Y = transformar celda en código

### Instrucciones básicas python
\# la almuadilla se utiliza para comentar instrucciones => a partir de la almuadilla el código no se ejecuta

Consejo: utilizad la almuadilla constantemente para anotar todos los pasos 

* Las instrucciones se ejecutan de arriba hacia abajo por orden
* Operaciones básicas
    * +: suma
    * -: resta
    * *: multiplicación
    * /: división
    * %: resto de una división. Ej: 7%3 es 1
    * \** potencia. Ej: $3^2$ se escribe en python como 3**2
* funciones básicas
    * print("texto a imprimir", 4, "tantos elementos como querais separados por comas")
* declarar una variable
    * x = 4
    * El nombre de la variable es x
    * "Guardamos" el valor 4 en la variable x.
    * Podemos utilizar esta variable después de guardarla
* Tipos de objetos (objeto es el valor que se puede guardar en una variable)
    * Numericos: 3, 2.4, -0.0003
    * Texto (Entre comillas): "hola clase"
    * booleanos: variables con dos valores True o False (lo veremos más adelante)
    * Otros


### Bucles fors
Un bucle en python es una instrucción que se repite varias veces

Los fors son un bucle que en cada iteración toma el valor de una lista

La instrucción que se hace dentro del for debe estar tabulada (hay que presionar la tecla tab del teclado para identar)

In [9]:
# range(n) es una función que retorna numeros del 0 al n (n entero)
# i es el nombre de a variable que toma el valor de 0 a 10
for i in range(10):
    print("En esta iteración, el valor de i es", i)

estoy en la iteración: 0
estoy en la iteración: 1
estoy en la iteración: 2
estoy en la iteración: 3
estoy en la iteración: 4
estoy en la iteración: 5
estoy en la iteración: 6
estoy en la iteración: 7
estoy en la iteración: 8
estoy en la iteración: 9


In [12]:
# Si utilizamos otro argumento en el range, nos dira desde donde empieza el valor de i
for i in range(5,10): # empezamos en 5 y llegamos hasta 10(sin incluirlo)
    print("En esta iteración, el valor de i es", i)

En esta iteración, el valor de i es 5
En esta iteración, el valor de i es 6
En esta iteración, el valor de i es 7
En esta iteración, el valor de i es 8
En esta iteración, el valor de i es 9


In [13]:
# Si utilizamos otro argumento en el range(tercer argumento), indicara el intervalo entre numeros
for i in range(0, 10, 2): # contamos de 2 en 2, desde 0 hasta 10(sin incluirlo)
    print("En esta iteración, el valor de i es", i)

En esta iteración, el valor de i es 0
En esta iteración, el valor de i es 2
En esta iteración, el valor de i es 4
En esta iteración, el valor de i es 6
En esta iteración, el valor de i es 8


##### Ejemplos
Podemos sumar numeros del 0 al 9

In [ ]:
suma = 0 # declaro una variable que sera el resultado de toda la suma
for i in range(10): # hago un bucle for que va desde i = 0 hasta i = 9
    suma = suma + i # voy acumulando la suma
print(suma)

### Ejercicio 1: Bucles fors
a) Imprime por pantalla los cuadrados de los numeros del 0 al 9. Completa el siguiente código. 

In [ ]:
for i in range(10):
    print(i)

b) Suma los cuadrados de los numeros del 0 al 9. Completa el siguiente código. 

In [ ]:
suma = 0
for i in range(10):
    suma = XXX
print(suma)

c) Suma los  numeros pares del 0 al 20. Completa el siguiente código. 

In [ ]:
suma = 0
for i in range(10):
    suma = XXX
print(suma)

d) Suma los numeros pares del 0 al 20. Completa el siguiente código. 

In [ ]:
suma = 0
for i in range(10):
    suma = XXX
print(suma)

e) Calcula la suma de los numeros elevados a 3 desde -3 hasta 9. Completa el siguiente código. 

In [ ]:
suma = 0
for i in range(XXX,9):
    suma = XXX
print(suma)

d) La condición 10%5==0 nos retorna True si el resto de la división entera 10/5 es 0 y False en otro caso, es decir, nos indica si 10 es divisible entre 5. Dado un numero cualquiera $n$ (poned uno como ejemplo), imprimid los numeros del 1 al $n$ que sean divisibles de $n$. 

In [14]:
# Pista: utilizad el siguiente código como inspiración y un for
n=10
print(5, "es divisible de", n, "es", n%5==0)

5 es divisible de 10 es True


### Apuntes
### Instrucciones básicas Numpy
Numpy es una libreria para operar con arrays (listas de numeros)

In [2]:
# cargo la libreria y le pongo un nombre corto (np)
import numpy as np

In [20]:
# declaro un array(vector) y lo guardo en una variable v
v = np.array([1,2,3,4,5])
print(v)

# este array tiene una longitud, podemos saber cual es mediante la funcion len(array)
print("La longitud de mi vector es", len(v))

# declaro un vector de 0 con 10 posiciones
v = np.zeros(10)
print(v)

# declaro un vector de 1 con 10 posiciones
v = np.ones(10)
print(v)

# declaro un vector del 0 al 10 (sin incluir el 10)
v = np.arange(10) # np.arange se comporta de forma parecida al range de los fors
print(v)

# np.arange se comporta de forma parecida al range de los fors
v = np.arange(10,20,2) # empiezo en 10 hasta 20 y salto de 2 en 2
print(v)

# puedo acceder a la información guardada en las posiciones del array con []. 
# Dentro de [] va el numero de posición: de 0 a la longitud -1
print(v[2]) 

# las posiciones empiezan en 0
print(v[0])

# la ultima posición es len(n)-1
print(v[len(v)-1])

# puedo cambiar el valor de la posición 2 (tercera posición) del array
v[2] = 99
print(v)

[1 2 3 4 5]
La longitud de mi vector es 5
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[0 1 2 3 4 5 6 7 8 9]
[10 12 14 16 18]
14
10
18
[10 12 99 16 18]


In [16]:
# declaro un array
v = np.arange(10)

# se puede operar facilmente todo el vector
print(v**2)
print(2*v)
print(v/10)

# se pueden sumar y restar vectores de la misma longitud
print(v+2*v+v**2)

[ 0  1  4  9 16 25 36 49 64 81]
[ 0  2  4  6  8 10 12 14 16 18]
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]
[  0   4  10  18  28  40  54  70  88 108]


## Ejercicios

### Ejercicios 2: Ejercicios numpy
a) Crea un vector de 10 posiciones del 10 al 20.

b) Utiliza el np.sum(v) para calcular la suma de todos los valores del array. Después cambia los valores de las posiciones 0 y 3 por 99. Imprime el vector resultante.

c) Crea un array $v$ del -100 hasta el 100. Define otro array que sea $v^2+2v$.

d) Ejercicio entregable. Interpreta el siguiente código. Comenta utilizando la almuadilla todos los pasos. ¿Se podría hacer un código más corto?

In [11]:
r = np.arange(10,30,3)+np.ones(7)*2
print(r)

i = 0
print(r[i])

i = i+1
print(r[i])

i = i+1
print(r[i])

i = i+1
print(r[i])

i = i+1
print(r[i])

i = i+1
print(r[i])

i = i+1
print(r[i])

[12. 15. 18. 21. 24. 27. 30.]
12.0
15.0
18.0
21.0
24.0
27.0


### Ejercicios 3: Numpy y fors
a) La suma acumulada de un vector v es la un vector del estilo de [v[0], v[0]+v[1], v[0]+v[1]+v[2], v[0]+v[1]+v[2]+v[3], ...]. Dado un vector, calcula la suma acumulada.

In [20]:
# rellenar XXX y YYY con ejemplos propios
v=np.arange(10)
suma=np.zeros(len(v))
for i in range(1, len(v)):
    suma[i] = suma[i-1]+v[i]
print(suma)

[ 0.  1.  3.  6. 10. 15. 21. 28. 36. 45.]


b) El siguiente código imprime los numeros del 10 al 1 en orden descendiente. Dado un array de 10 posiciones (cread uno como ejemplo), escribe un código que imprima los valores del array desde la última posición hasta la primera

In [4]:
n = 10
for i in range(n):
    print(n-i-1)

9
8
7
6
5
4
3
2
1
0


In [9]:
n = 10
v = np.arange(10)*2
for i in range(n):
    print(v[n-i-1])

18
16
14
12
10
8
6
4
2
0


c) La suma de dos vectores $v$ y $w$ de la misma longitud en Numpy se puede escribir $v+w$. Si no pudieramos hacer esta operación deberiamos sumar posición a posición. Modifica el código sigüiente para imprimir la suma de cada posición.

In [19]:
v = np.arange(10)
w = np.ones(10)
print(v+w) # esta es la forma de numpy
for i in range(10):
    # modifica a partir de aqui
    print(v[i])
    print(w[i])

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
0
1.0
1
1.0
2
1.0
3
1.0
4
1.0
5
1.0
6
1.0
7
1.0
8
1.0
9
1.0


d) Ejercicio entregable. Un número primo $n$ es un número que solo tiene como divisores el 1 y $n$. Completad y comentad cada paso del siguiente código que nos dice si un número es primo.

In [18]:
# pista: No es necesario Numpy
n = 7 # 7 es primo
es_primo = True
for i in range(XXX, XXX):
    es_primo = n%i!=0

# deberia imprimirse True
print(es_primo)

True
